
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

#    url: jdbc:mysql://120.78.157.175:3306/gzjc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://120.78.157.175:3306/gzjc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jc
